### ISSUE TITLE
Make candidate markers in Toggle List configurable

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [yzhang-gh/vscode-markdown#1022]
## Proposal

Currently, labels of list can be toggled as follows:
(Repeat `markdown.extension.editing.toggleList` multiple times.)

`-` → `*` → `+` → `1.` → `1)` → none → `-` (loop)

However, I do not use `*`or `+` or `1)`, and it is very stressful to go through these to cancel the list.
Is it possible to allow labels of list to be set by the user?

Like this:

```json
  "markdown.extension.toggleList.label": [
    "-",
    "1.",
  ]
```

Thanks for your work on this very handy extension!

**Comment by yzhang-gh** [comment]
Thanks for the suggestion.

I agree with you but I won't have enough time in the near future. For anyone who is interested, here is the code

https://github.com/yzhang-gh/vscode-markdown/blob/bd32c94a3455eb65ed568732976bd0539e9a8fc4/src/formatting.ts#L220-L240

**Comment by Yarakashi-Kikohshi** [comment]
Thank you for reply. I hope someone help me!!

**Comment by scbzfarmingtest** [comment]
It seems that I need this feature a lot as well and thanks for all the help from here and #1145.  
Sorry that I cannnot read the source code and I just wonder if there could be a setting instead of running `toggle list` command every time?

**Comment by yzhang-gh** [comment]
> I just wonder if there could be a setting instead of running `toggle list` command every time?

You can assign a key binding to that command (please see https://code.visualstudio.com/docs/getstarted/keybindings)

**Comment by scbzfarmingtest** [comment]
Thanks for reply and sorry if there are any ambiguous expressions. What I mean is if there could be entries in extension setting (like `markdown.extension.toggleList` and `markdown.extension.toggleListArray`) and after clicking it, the labels will automatically change according to the array and the number of `tab` in the beginning of the line, similarly as unordered list does.

**Comment by yzhang-gh** [comment]
Looks like it can be solved by the original proposal in this thread. Otherwise you can provide concrete examples to illustrate your use cases.

**Comment by scbzfarmingtest** [comment]
Sorry I just realised `Toggle List` **does not** change output, so I might misunderstand...
But let me try to explain the features I expect...  
So I wonder if there could be 2 entries (rather than only first): `markdown.extension.toggleList.label` and `markdown.extension.enable.autotoggleList` (I edited the name in my last comment to make them more clear). Then, for example:
```  
"markdown.extension.enable.autotoggleList": "off" 
"markdown.extension.toggleList.label": [
    "1.",
    "1)",
    "(1)",
  ]
```
Then when typing, 
```
    1. A
    2. B
        1. A.a
        2. B.b
            1. A.a.A
```
and when the cursor is in the 3rd line, using command `Markdown All in One: Toggle List` will result in:
```
    1. A
    2. B
        1) A.a
        2. B.b
            1. A.a.A
```
and use `Markdown All in One: Toggle List` again:
```
    1. A
    2. B
        (1) A.a
        2. B.b
            1. A.a.A
```
But if set `markdown.extension.enable.autotoggleList` as `on`, then **without** command `Markdown All in One: Toggle List`, it will automatically result in:
```
    1. A
    2. B
        1) A.a
        2) B.b
            (1) A.a.A
```
**Of course, I wish the output follows as well...**

**Comment by yzhang-gh** [comment]
Thanks for the information. This has been discussed before in #145 and #359 and we finally decided to implement the `toggle list` command. I have reopened #359 to track this request.
