### ISSUE TITLE
Support Markdown math in .ipynb files

### ISSUE THREAD

**Issue by yzhang-gh** [yzhang-gh/vscode-markdown#1030]
当我禁用内置的 Markdown Math 模块时，我在 .ipynb 文件中 latex 就失效了，虽然 jupyter 我用的并不多。

我发现 markdown all in one 似乎并不支持 .ipynb 文件中的 markdown 部分。

是否可以支持一下呢？

_Originally posted by @Real-king-Ph in https://github.com/yzhang-gh/vscode-markdown/issues/1029#issuecomment-951472843_

**Comment by Lemmingh** [comment]
I'm afraid this problem is beyond us.

[Jupyter](https://jupyter.org/)'s Markdown rendering is powered by a customized [Marked](https://github.com/markedjs/marked), [MathJax](https://www.mathjax.org/), and [CodeMirror](https://github.com/codemirror). As I noted in #1029, the grammar and semantics of Jupyter's Markdown diverges significantly from CommonMark and its derivatives.

Conclusion: It's technically impossible for a CommonMark-centered system to support things from a flavor that is not a derivative of CommonMark.

BTW, VS Code is still struggling with Jupyter's world:

* <https://github.com/microsoft/vscode/issues/133390>
* <https://github.com/microsoft/vscode/issues/135261>
* <https://github.com/microsoft/vscode/issues/141905>

---

我认为该问题不在我们的能力或关注范围内。

[Jupyter](https://jupyter.org/) 的 Markdown 支持基于一套魔改的 [Marked](https://github.com/markedjs/marked)、[MathJax](https://www.mathjax.org/) 和 [CodeMirror](https://github.com/codemirror)。正如我在 #1029 中所说，无论是语法还是语义，Jupyter 的 Markdown 都跟 CommonMark 衍生物差别巨大。

结论：从技术上讲，在一个以 CommonMark 为中心的系统中，不可能支持来自非 CommonMark 衍生物的东西。

顺便一提，VS Code 似乎也挺愁得慌：

* <https://github.com/microsoft/vscode/issues/133390>
* <https://github.com/microsoft/vscode/issues/135261>
* <https://github.com/microsoft/vscode/issues/141905>
