### ISSUE TITLE
Markdown citation syntax not highlighted correctly

### ISSUE THREAD

**Issue by daijiang** [yzhang-gh/vscode-markdown#1038]
Hi,
I am writing a paper with markdown using VSCode. But the citations were not highlighted correctly.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1696911/141014292-55a9cd16-0618-46c2-9397-8593c57e8408.png">

Any idea how to fix this? 
Thanks!

**Comment by Lemmingh** [comment]
Do you mean [shortcut reference link](https://spec.commonmark.org/0.30/#shortcut-reference-link)?

Such things require semantic information, which cannot be achieved with [TextMate grammar](https://github.com/microsoft/vscode-markdown-tm-grammar).

I think [Semantic Highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) is the way out. But as discussed somewhere before, we need to get a Markdown processor that provides very precise source mapping.

---

In case you're interested in VS Code's architecture of [syntax highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide):

* <https://github.com/microsoft/vscode/issues/77140>

**Comment by daijiang** [comment]
It is not shortcut reference link since `[@citationKey]` it is regular text.
I think it just requires to update the match pattern to highlight. For example, in the attached screenshot, line 2 works (highlighted) but line 3 was not highlighted (because of a space after `;`).
Thanks!

**Comment by yzhang-gh** [comment]
Those `[@text]` in line 1 and line 2 happen to get highlighted because VS Code _thinks_ they are reference links.
There is no concept of citations in Markdown. So the result is as expected.

<img src="https://user-images.githubusercontent.com/7588612/141048620-861c7d29-b183-41c5-be48-881c0d3d8b40.png" width="526">

**Comment by yzhang-gh** [comment]
Those `[@text]` in line 1 and line 2 happen to get highlighted because VS Code _thinks_ they are reference links.
There is no concept of citations in Markdown. So the result is as expected.

<img src="https://user-images.githubusercontent.com/7588612/141048620-861c7d29-b183-41c5-be48-881c0d3d8b40.png" width="526">

**Comment by daijiang** [comment]
So basically there is no way to get all citations correctly highlighted in VS Code?

**Comment by yzhang-gh** [comment]
You can use [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) extension.
Of course a little knowledge about regular expressions is required. Probably you can try `\[@[\]]*\]`.

**Comment by daijiang** [comment]
Thanks! I'll check that out.
