### ISSUE TITLE
Add option to convert line breaks to <br> without adding two spaces to end of line

### ISSUE THREAD

**Issue by Mark-L6n** [yzhang-gh/vscode-markdown#1107]
## Proposal

Add option to convert line breaks to `<br>` without adding two spaces to end of line

markdown-it has an option `breaks` which if set to `true` converts line breaks to `<br>`

We have a large number of Markdown files that are formatted in this manner.  Currently they are almost unreadable in VS Code, as a line which does not end in 2 spaces is converted to an HTML "softbreak", as in:

``` html
line 1
line 2
```

instead of a hardbreak as in:

``` html
line 1<br>
line2
```

Also, for many users, this would be much easier for typing Markdown, not needing to remember to type 2 spaces at the end of each line.  And HTML softbreaks are rarely required for most users.   
Additionally, this would be consistent with current github-style markdown (as used in the editor I'm typing this in.)

Please create an option to display line breaks as `<br>`.  Thanks!

## References

https://github.com/markdown-it/markdown-it  lists as an option: 
`breaks:       false,        // Convert '\n' in paragraphs into <br>`

**Comment by Lemmingh** [comment]
Could you clarify your idea? I can see three different things in your proposal.

* Expose `markdown-it`'s `breaks` option. Already implemented by VS Code as `markdown.preview.breaks`. We respect **VS Code's settings**.

* Make [Hard Line Break](https://spec.commonmark.org/0.30/#hard-line-breaks) and [Paragraph](https://spec.commonmark.org/0.30/#paragraphs) ending visible in the editor. Same as #881. We'll release that **experimental** feature someday.

* Convert Hard Line Break and Soft Line Break to [Inline Raw HTML](https://spec.commonmark.org/0.30/#raw-html). We won't do that due to tons of **usability and reliability problems**.

**Comment by yzhang-gh** [comment]
From my understanding it is the first case. So you can simply set `markdown.preview.breaks` to `true` @Mark-L6n.

**Comment by Mark-L6n** [comment]
Thanks very much for the answer -- I had searched for this but not found it.
