### ISSUE TITLE
Pressing enter and deleting md files on vscode version 1.67.2 lags badly

### ISSUE THREAD

**Issue by seyeeL** [yzhang-gh/vscode-markdown#1129]
It's very slowly

**Comment by yzhang-gh** [comment]
It is hard to tell why this happens as there is no enough information from your description.

You can first check out the FAQ https://github.com/yzhang-gh/vscode-markdown#q-the-extension-is-unresponsive-causing-lag-etc-performance-issues (making sure it is not because of other extensions)

Many extensions have been found to cause the lag (see #423, #855, #969)

Also, this may also be helpful

> - (As a last resort, you may choose to delete `onXXXKey` keys through [VS Code's Keyboard Shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings) if you do not need the [list editing feature](https://github.com/yzhang-gh/vscode-markdown#list-editing) at all.)
