### ISSUE TITLE
option for disabling path auto-completion

### ISSUE THREAD

**Issue by HenryC-3** [yzhang-gh/vscode-markdown#1141]
## context

vscode now has [built-in path IntelliSense for markdown](https://github.com/microsoft/vscode/issues/140602#issue-1100965100)(enable by default), which is similar to the path auto-completion feature.

When both features are enabled,  there is a redundant path suggestion.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/41246463/175907970-3c777f82-bfc1-4aaf-a766-13fbee22a5fa.png">

## Proposal

provide an option to disable path auto-completion

## References

-  https://github.com/microsoft/vscode/issues/140602#issue-1100965100

**Comment by skylon07** [comment]
I feel like there must be a way to "override" default Intellisense behavior for specific languages...
@yzhang-gh I did some digging, and I discovered something that might be worth trying (I would try myself, but I can't seem to figure out how to actually run/debug the extension). In `package.json`, add a "markdown" entry like this:
```
"contributes": {
    ...
    "markdown": ["markdown-language-features"],
    ...
}
```

I might be totally off-base here, since I don't do much extension development myself; perhaps this was some "old way" of doing this. Nonetheless, if you think it's worth it, give it a try! I wonder if telling VSCode the extension contributes the "markdown-language-feature" if it will disable the built-in Intellisense stuff, avoiding this issue altogether.

**Comment by yzhang-gh** [comment]
Thanks for the information. Did you find any documentation for this API? We have similar entries in the `package.json`

https://github.com/yzhang-gh/vscode-markdown/blob/577dbb420916eecc4694591a3e033c8b8d9261a0/package.json#L547-L551

but I haven't seen the entry mentioned above.

**Comment by yzhang-gh** [comment]
I have disabled the path completions of this extension in v3.5.1.

**Comment by skylon07** [comment]
That works too, thanks!
