### ISSUE TITLE
Auto-TOC error when emoji in the head

### ISSUE THREAD

**Issue by imhuay** [yzhang-gh/vscode-markdown#1181]
## Problem

Auto-TOC error when emoji in the head

## How to reproduce

```markdown
- [Test 🔗](#test-)
- [Test 🔗](#test--1)
- [Test 🔗](#test--2)

## Test 🔗
## Test 🔗
## Test [🔗](https://www.google.com/)
```

**Comment by imhuay** [comment]
#1159

**Comment by yzhang-gh** [comment]
Thanks for the feedback. What is your expected output?

**Comment by imhuay** [comment]
It seems to be a problem with markdown itself, as it doesn't work when there are multiple identical titles with emojis.

```
- [Test 🔗](#test-🔗)
- [Test 🔗](#test-🔗-1)  <!-- not work -->

## Test 🔗
## Test 🔗  

---

- [Test](#test)
- [Test](#test-1)  <!-- work -->

## Test
## Test
```

In addition, has option `markdown.extension.toc.encodeUri` been removed?

**Comment by yzhang-gh** [comment]
Markdown by itself doesn't generate id for heading, i.e., it simply converts `# Heading` to `<h1>Heading</h1>` (rather than `<h1 id="foo">Heading</h1>`).

Different Markdown implementations have their own id-generation methods (i.e., slugify functions), which is out of control of the Markdown source file. If you put your Markdown file on GitHub, you need to follow GitHub's conventions, which is

![Screenshot from 2022-10-09 11-27-15](https://user-images.githubusercontent.com/7588612/194736865-a47aa712-476f-46be-b613-6f394a9f92d3.png)

> In addition, has option `markdown.extension.toc.encodeUri` been removed?

I'm not sure but I don't remember we had this option before.

**Comment by imhuay** [comment]
Thank you for your explanation.
Because the link checking feature for markdown added in VSCode 1.72 is inconsistent with Github's behavior which made me confused. I already know it's not a BUG.

**Comment by yzhang-gh** [comment]
> The option `markdown.extension.toc.encodeUri` was mentioned in [#90 (comment)](https://github.com/yzhang-gh/vscode-markdown/issues/90#issuecomment-371453888)

Ah, it was too long ago. I believe it has been replaced by the `toc.slugifyMode`.
