### ISSUE TITLE
Extension spams Extension Host log with warnings

### ISSUE THREAD

**Issue by AndersHogqvist** [yzhang-gh/vscode-markdown#1213]
### What's the problem
This extension spams the Extension Host log with the following warning:
```
2022-12-14 13:22:25.723 [warning] [yzhang.markdown-all-in-one] Accessing a window scoped configuration for a resource is not expected. To associate 'markdown.extension.extraLangIds' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.
```

This is printed about 2 times a second!

### What's the expected result
No warnings

### How to reproduce

1. Install the extension
2. I'm not sure if you have to do anything else actually, I haven't even opened any md file.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This `extraLangId` was introduced in the latest major update, which added the support for more languages (e.g. R Markdown). This extension will be activated under several conditions

https://github.com/yzhang-gh/vscode-markdown/blob/35a71db8767bdd8198d050b05e767b67cd8a570c/package.json#L27-L33

(also see #1195)

As for the warning, it is a bug. Will try to fix it later today.

**Comment by yzhang-gh** [comment]
Well, I could not see those warnings on my machine. But it should have been fixed in the latest [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/3696016687) (download it in the "Artifacts" section).

![image](https://user-images.githubusercontent.com/7588612/207628481-6d86ede4-ba61-415a-a630-4a99bf624420.png)

![image](https://user-images.githubusercontent.com/7588612/207628632-25ce789c-537d-477a-902c-92225f8b92cf.png)
