### ISSUE TITLE
Extension not activated when there is no `search.exclude` in settings.json

### ISSUE THREAD

**Issue by mgerzabek** [yzhang-gh/vscode-markdown#1357]
### What's the problem
I integrated the extension into Eclipse Theia. After launching I got the error message `Activating extension 'Markdown All in One' failed: Cannot convert undefined or null to object` and the extension was not actived.

### What's the expected result
The extension should activate also with empty (null, undefined) `search.exclude` pattern.

### How to reproduce

1. Download Eclipse [Theia Blueplrint](https://github.com/eclipse-theia/theia-blueprint)
2. Add the extension `markdown-all-in-one` to [package.json](https://github.com/eclipse-theia/theia-blueprint/blob/master/package.json), copy `"markdown-all-in-one": "https://open-vsx.org/api/yzhang/markdown-all-in-one/3.5.1/file/yzhang.markdown-all-in-one-3.5.1.vsix",` into the `theiaPlugins` section.
3. Run `yarn && yarn build:dev && yarn download:plugins` followed by `yarn electron package`
4. Run `yarn electron package:preview`

### Other information
The problem is in the constructor of `MdCompletionItemProvider` in the block where the exclude patterns are constructed.
```js
const Always_Exclude = ["**/node_modules", "**/bower_components", "**/*.code-search", "**/.git"];
        const excludePatterns = new Set(Always_Exclude);
        if (manager_1.configManager.get("completion.respectVscodeSearchExclude", folder)) {
            const vscodeSearchExclude = manager_1.configManager.getByAbsolute("search.exclude", folder);
            for (const [pattern, enabled] of Object.entries(vscodeSearchExclude)) {
                if (enabled) {
                    excludePatterns.add(pattern);
                }
            }
        }
```
`manager_1.configManager.getByAbsolute("search.exclude", folder)` returns undefined and then the `for()` breaks.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Never know there is a way to run this inside Eclipse 😲.

Can you change your settings somewhere so that the `completion.respectVscodeSearchExclude` is `false`? I can add a simple null check here but in general this extension only targets vscode, so there might be more vscode-related incompatibility in Eclipse.

**Comment by madmini** [comment]
I can confirm this workaround fixes the issue in Theia IDE 1.50.100: no error message, extension loads and mostly works. Could you add the null check anyway? It seems Theia is still missing `search.exclude` (but has `files.exclude`). see https://github.com/eclipse-theia/theia/issues/7273#issuecomment-594645876

Note that _Theia IDE_ (formerly also _Theia Blueprint_) is the [VSCode alternative](https://blogs.eclipse.org/post/mike-milinkovich/eclipse-theia-and-vs-code-differences-explained) of the Eclipse Foundation, not the _Eclipse_ IDE.
For information on extension support in Theia see <https://theia-ide.org/docs/user_install_vscode_extensions/#compatibility>.

**Comment by madmini** [comment]
With the workaround some stuff is still broken:

- all actions (except batch html conversion) are **missing from the palette**, but it seems most of the functionality is still there:
  - the batch html conversion works perfectly
  - table of content creation is missing, but if one is created in vscode, it is detected and properly updated in Theia
- **pasting links** produces console error `Command with id 'editor.action.insertSnippet' is not registered.` I believe this is because Theia does not support snippets yet.  (see eclipse-theia/theia#3686)
- there are two _Open Preview to the Side_ buttons; one of them opens the stock markdown preview while the other opens the correct (from this extension) preview

Everything else I have tested so far has worked perfectly!

**Comment by yzhang-gh** [comment]
Hi, thanks for the information. Would you minding opening a PR for the null check? It should be very simple but I would like to also add a few comments about Eclipse Theia along with the code change and I believe you definitely have more context than me.
