### ISSUE TITLE
Pressing Enter in a list when there are autocomplete options but not "Accept Suggestion On Enter" does not continue the list

### ISSUE THREAD

**Issue by dan-nectry** [yzhang-gh/vscode-markdown#1367]
### What's the problem

Pressing `enter` in a list when there are autocomplete options but "Accept Suggestion On Enter" is set to off does not continue the list.  For instance, in a bulleted list, pressing enter will not make a new bullet on the next line.

### What's the expected result

Since "Accept Suggestion On Enter" if off, I would expect that, regardless of whether there are autocomplete suggestions available, pressing enter would create a new line with list formatting.

### How to reproduce

1. Set "Accept Suggestion On Enter" to "off"
2. With the language set to Markdown, start a list (either bulleted or numbered).
3. Have the last word of a line of the list have autocomplete options.  Do not accept any of these options.  Do not escape or otherwise cancel the autocomplete.
4. Press enter.

**Comment by dan-nectry** [comment]
@yzhang-gh Is there any more info you need to categorize/triage this problem?  Or, is this a known bug that I didn't manage to find in the issue tracker?

**Comment by yzhang-gh** [comment]
Thanks for your feedback, and sorry I actually have read this but forgot to reply.

This is possible as the "continuing list" command won't be invoked if the suggest widget is visible

https://github.com/yzhang-gh/vscode-markdown/blob/09be4abe62858989d3ab00a0896a442b3fa34052/package.json#L251

It was impossible to access user settings in the static `package.json` but fortunately should be okay in the recent VS Code versions.
I will need some time to check it and hopefully it can be fixed in this weekend, when I plan to release a new version of this extension.

**Comment by yzhang-gh** [comment]
You can try it out using the latest dev build
https://github.com/yzhang-gh/vscode-markdown/actions/runs/7322269176/artifacts/1134210918

**Comment by peaceshi** [comment]
> You can try it out using the latest dev build https://github.com/yzhang-gh/vscode-markdown/actions/runs/7322269176/artifacts/113421

分组应该跟之前一样在同一组里，否则如果有多个需要在工具栏显示操作的插件就会被打乱顺序。而且vsc只显示前几个注册的，后面的会被放到下拉菜单里。
![image](https://github.com/yzhang-gh/vscode-markdown/assets/10380828/ff2f18ff-d06d-49d3-bcfb-d796303f082a)
![image](https://github.com/yzhang-gh/vscode-markdown/assets/10380828/1bebfa10-cba8-4b07-94b3-c3d6eec6847e)
