### ISSUE TITLE
Signicant Latency For `markdown.extension.on***`

### ISSUE THREAD

**Issue by hnyls2002** [yzhang-gh/vscode-markdown#1372]
I have experienced similar problems(#423) but haven't installed Spell Right extensions.

When editing `.md` files in vscode and enabling the `markdown-all-in-one` extension, I encounter significant latency when pressing Backspace and Enter. Sometimes, the backspace even responds after the next input character.

I first thought the significant latency may be brought by the latency from server to client (using SSH), but when I turned off the shortcuts.

- `markdown.extension.onBackspace`
- `markdown.extension.onEnterKey`

The problems are solved. What are these shortcuts used for? And why is there such significant latency?

**Comment by yzhang-gh** [comment]
Thanks for the feedback. This is a very common issue and it is always because of conflicts between extensions. It could be Spell Right, or Todo Tree and many more (I have no idea, but you will see similar issues for the Vim extension as it overwrites all the keys...). If you are interested, you can test it again will all other extensions disabled (see instructions in #855).

As for your question, you can see https://github.com/yzhang-gh/vscode-markdown/issues/969#issuecomment-1773835582.
