### ISSUE TITLE
Toggle checkbox keybinding no longer works in version 3.6.0 or newer

### ISSUE THREAD

**Issue by joneshf-dd** [yzhang-gh/vscode-markdown#1381]
### What's the problem

Toggle checkbox keybinding no longer works in version 3.6.0 or 3.6.1. This behavior works in 3.5.1.

### What's the expected result

When pressing the toggle checkbox keybinding (Option+C on macOS by default), it should toggle the checkbox.

### How to reproduce

1. Install 3.6.0 or 3.6.1.
2. Make a checkbox
    ```Markdown
    - [ ] Something
    ```
3. Press Option+C (or the equivalent).
4. It will not toggle the checkbox.

### Other information

You can validate that it still works in 3.5.1 by downgrading the extension and running through the same reproduction steps.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I forgot to mention that this key binding was removed for Mac as it overrides a character in other languages (#1285). You can assign it back to the command `markdown.extension.checkTaskList`. This is also the case for `markdown.extension.editing.toggleStrikethrough` which had the key binding alt+s.

**Comment by xiecang** [comment]
My reassignment to Option+C doesn't seem to work, do I need to bind it to another shortcut?

**Comment by yzhang-gh** [comment]
You can use [this method](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings) to check what VS Code is doing after you pressed the key binding.

![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/03a8358d-5ee5-4e9b-ae28-6cddf2483cb3)

**Comment by xiecang** [comment]
When I press option+C, I get this log:

2024-01-16 21:37:54.683 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-01-16 21:37:54.700 [info] [KeybindingService]: \ Keyboard event cannot be dispatched
2024-01-16 21:37:54.700 [info] [KeybindingService]: / Received  keydown event - modifiers: [alt], code: AltLeft, keyCode: 18, key: Alt
2024-01-16 21:37:54.700 [info] [KeybindingService]: | Converted keydown event - modifiers: [alt], code: AltLeft, keyCode: 6 ('Alt')
2024-01-16 21:37:54.700 [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
2024-01-16 21:37:55.007 [info] [KeybindingService]: / Soft dispatching keyboard event
2024-01-16 21:37:55.007 [info] [KeybindingService]: | Resolving alt+[KeyC]
2024-01-16 21:37:55.007 [info] [KeybindingService]: \ No keybinding entries.
2024-01-16 21:37:55.007 [info] [KeybindingService]: / Received  keydown event - modifiers: [alt], code: KeyC, keyCode: 67, key: ç
2024-01-16 21:37:55.008 [info] [KeybindingService]: | Converted keydown event - modifiers: [alt], code: KeyC, keyCode: 33 ('C')
2024-01-16 21:37:55.008 [info] [KeybindingService]: | Resolving alt+[KeyC]
2024-01-16 21:37:55.008 [info] [KeybindingService]: \ No keybinding entries.
2024-01-16 21:37:55.253 [info] [KeybindingService]: + Ignoring single modifier alt due to it being pressed together with other keys.

this is my shortcut configuration.
<img width="1465" alt="image" src="https://github.com/yzhang-gh/vscode-markdown/assets/16369161/7f62232e-fb8e-471c-b0d3-e39b0348bb4c">

**Comment by yzhang-gh** [comment]
That is because you set `when` to `false`, which means never. Try e.g. (remove the `!isMac` condition)

https://github.com/yzhang-gh/vscode-markdown/blob/cfd568bf37223ac60d104f7dc6b2cd79ae130fda/package.json#L315-L317

**Comment by xiecang** [comment]
> That is because you set `when` to `false`, which means never. Try e.g. (remove the `!isMac` condition)
> 
> https://github.com/yzhang-gh/vscode-markdown/blob/cfd568bf37223ac60d104f7dc6b2cd79ae130fda/package.json#L315-L317

Thank you so much, the changes worked perfectly following your configuration.

**Comment by joneshf-dd** [comment]
> Thanks for the feedback. I forgot to mention that this key binding was removed for Mac as it overrides a character in other languages (#1285). You can assign it back to the command `markdown.extension.checkTaskList`. This is also the case for `markdown.extension.editing.toggleStrikethrough` which had the key binding alt+s.

I see. Any chance the extension itself could change the key binding to something else? I don't really care if I use Option+C or something else, but I'd like to not have to remember to override the keybinding for different macOS machines.

**Comment by Gorzas** [comment]
Not much experience using MacOS, but could be the key binding be `Ctrl + c` and `Ctrl + s`? Or maybe make it configurable per user.

**Comment by yzhang-gh** [comment]
Hi, sorry for the late reply. It is hard to find an easy-to-remember but not-yet-been-used key binding. (There are many issues in this repository complaining about the default key bindings.)

> I'd like to not have to remember to override the keybinding for different macOS machines

@joneshf-dd I would suggest [sync your settings/profiles](https://code.visualstudio.com/docs/editor/settings-sync) with a GitHub account. VS Code had been developed/polished this feature for a long time and I feel it is easy to use.

> Or maybe make it configurable per user

@Gorzas You can configure the key binding with [VS Code's keyboard shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings) (The commands are `markdown.extension.checkTaskList` and `markdown.extension.editing.toggleStrikethrough`). And again, it can be synced with an account.
