### ISSUE TITLE
Request for CSS compatibility in markdown preview feature

### ISSUE THREAD

**Issue by hazeyez** [yzhang-gh/vscode-markdown#1425]
I find that no CSS works in preview mode - 

Whether it be external in a styles.css file and used in...
```html
<head>
    <link rel="stylesheet" href="styles.css">
</head>
```
and styles.css contains:
```css
.resize-image {
    height: 65%;
    width: auto;
}
```

Or internal...
```html
<head>
    <style>
        .resize-image {
            height: 65%;
            width: auto;
        }
    </style>
</head>
```
And in either of the above cases, brought into the html tag within the markdown file such as:

`<img src="image.jpg" class="resize-image">`

*OR* 

Whether it be inline within the html itself, in this case using the \<img\> tag:

`<img src="image.jpg style="height: 65%; width: auto;">`

---

In this example I am just using <img> tag as an example, but all CSS styling features would be good to have. 

It would be fantasic to have this feature within markdown preview mode available, especially since your markdown extension is the # 1 markdown extension for Visual Studio Code!

**Comment by yzhang-gh** [comment]
Not sure whether it is because of the `<head>` scope. I always use it like this

![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/e9993865-e7f7-44da-b426-f3d0363248ab)

As for external CSS files, you can set the `markdown.styles` option (which is provided by VS Code itself). Although I remember there are some restrictions (e.g. local files should be inside the current folder?) due to security concerns.

**Comment by hazeyez** [comment]
Interesting, I'll give it a shot. Thank you for replying and offering a solution! As long as there is some way to do it.. even if not traditional then that's fine, I suppose. However would love to see standard compatibility one day given the popularity of the extension. I hope you consider it!

Nice work by the way, bravo.
