### ISSUE TITLE
command "markdown.showPreviewToSide" not found

### ISSUE THREAD

**Issue by RedTailBullet** [yzhang-gh/vscode-markdown#372]
**VSCode versions**:  
Version: 1.31.0  
Commit: bb1e228e30ce43ebb361c84fdf2f0d4fb7fda6ce  
Date: 2019-02-09T14:23:42.615Z  
Electron: 2.0.17  
Chrome: 61.0.3163.100  
Node.js: 8.9.3  
V8: 6.1.534.41  
OS: Linux x64 4.20.7-arch1-1-ARCH  

Markdown All in One version: 2.0.1  

#### What is the problem?

As the title implied, this is yet another command not found issue. All markdown-related commands are not found. I tried all steps, it keeps happening. I've checked the log from extension host, the extension is loaded normally without any warning or error.

#### How can I reproduce it?

I really don't know. I've been using this for quite a long time and this never happen.

#### Is there any error message in the console?

```
ERROR: workbench.main.js:2561 Error: command 'markdown.showPreviewToSide' not found
    at Proxy.t._tryExecuteCommand (workbench.main.js:3226)
    at workbench.main.js:3225
    at <anonymous>
```

And this might be interesting:

```
/usr/lib/code/out/vs/workbench/workbench.main.js:3541 Activating extension 'vscode.markdown-language-features' failed: Invalid regular expression: /(\p{Alphabetic}|\p{Number})+/: Invalid escape.
```

And the full stack:
```
[Extension Host] Here is the error stack:  SyntaxError: Invalid regular expression: /(\p{Alphabetic}|\p{Number})+/: Invalid escape
	at new RegExp (<anonymous>)
	at t.activate (/usr/lib/code/extensions/markdown-language-features/dist/extension.js:1:49711)
	at Function.t._callActivateOptional (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:741:354)
	at Function.t._callActivate (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:741:25)
	at /usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:740:206
	at <anonymous>
```

**Comment by yzhang-gh** [comment]
It seems that your vscode installation is broken. (The `vscode.markdown-language-features` is a built-in extension of vscode)

I would suggest reinstalling your vscode first.

If that won't help, let's see whether we can have more information.

**Comment by RedTailBullet** [comment]
> It seems that your vscode installation is broken. (The `vscode.markdown-language-features` is a built-in extension of vscode)
> 
> I would suggest reinstalling your vscode first.
> 
> If that won't help, let's see whether we can have more information.

It seems that this is indeed a bug with markdown-language-feature and they are aware of it. Thanks for your help.

**Comment by surajkumar26** [comment]
Just Disable & Re-Enable Auto open Markdown Preview extension.

**Comment by AlbertVilaCalvo** [comment]
This error (command 'markdown.showPreviewToSide' not found) has happened to me today doing the following:

- I had a folder with some files, which I had previously opened with VSCode. One of these files is a markdown file, named `Notes.md`.
- With VSCode opened, but not opened on this folder, I renamed `Notes.md` to `README.md`.
- Then I opened the folder containing `Notes.md/README.md` by doing `code .` at the terminal. Since VSCode had previously opened that folder, it tried to show `Notes.md`, but since had renamed this file, there was an error (at the top of VSCode I believe) saying that it could not find `Notes.md`. I don't remember the exact error.

After all this, clicking the icon to preview the markdown VSCode showed the error "command 'markdown.showPreviewToSide' not found" at the bottom right.

**Comment by LinqLover** [comment]
Restarting VS Code also solved the issue for me.

**Comment by vivekup3424** [comment]
Yeah, I have also seen that restarting the vscode  can solve this issue

**Comment by TheDevelolper** [comment]
Restarting vs code doesn't work for me on Ubuntu.
