### ISSUE TITLE
the support of graphviz (dot) language

### ISSUE THREAD

**Issue by Yeba** [yzhang-gh/vscode-markdown#438]
the AllInOne do not support Graphviz (dot) language, but 
 [Graphviz Markdown Preview](https://marketplace.visualstudio.com/items?itemName=geeklearningio.graphviz-markdown-preview) works, can AllInOne do this?

#### What is the problem?
no problem, just suggest

#### How can I reproduce it?
no problem, just suggest

#### Is there any error message in the console?
no problem, just suggest

**Comment by yzhang-gh** [comment]
Actually, it is beyond Markdown's scope. We are supporting [CommonMark](https://spec.commonmark.org/0.29/), [GFM](https://github.github.com/gfm/) and some of the most popular features.

Personally, I don't feel like adding this. The reason is there are too many dialects like UML graph, flow chart and mermaid etc. (#328, #182 and #69)

But PRs are always welcomed.

**Comment by yzhang-gh** [comment]
Should be resolved with v3.0.0. Just install both extensions and they can work together.
