### ISSUE TITLE
Unknown configuration setting for `markdown.extension.toc.tabSize`

### ISSUE THREAD

**Issue by chenrui333** [yzhang-gh/vscode-markdown#464]
>  doesn't work? -> update vscode

vscode is the latest

> doesn't work? -> reinstall this extension

I have reinstalled the extension

#### What is the problem?

I keep getting `markdown.extension.toc.tabSize` when I tried to update the default indentation from 2 to 1.

![image](https://user-images.githubusercontent.com/1580956/59153700-a56ca400-8a2e-11e9-8736-10531ab4f8ec.png)

#### How can I reproduce it?

Here is my relevant setting on toc config:
```
	"markdown.extension.toc.githubCompatibility": true,
	"markdown.extension.toc.orderedList": false,
	"markdown.extension.toc.tabSize": 1,
	"markdown.extension.toc.updateOnSave": true,
```

Other than `markdown.extension.toc.tabSize`, others work for me pretty well.

#### Is there any error message in the console?

I did not see anything interesting in the "Developer Tools".

**Comment by yzhang-gh** [comment]
This setting is replaced by `markdown.extension.list.indentationSize` since [v2.0.0](https://github.com/yzhang-gh/vscode-markdown/blob/master/CHANGELOG.md#200-20190119).

If it is `inherit`, the `tabSize` of the editor will be used (which can be found at the right bottom corner).

(Other settings can be viewed [here](https://github.com/yzhang-gh/vscode-markdown#supported-settings))

BTW, `1` is not a valid indentation size for Markdown list (at least 2).

**Comment by chenrui333** [comment]
`markdown.extension.list.indentationSize: "adaptive"` works for me.

Do you know how I can configure `tabSize` across the board?

**Comment by yzhang-gh** [comment]
You can change `editor.tabSize` to 2 globally. Or put this in the `settings.json`

```json
"[markdown]": {
    "editor.tabSize": 2
}
```

which means Markdown-specific setting.
