### ISSUE TITLE
Latest version, latest VSC, macOS Mojave - lame update

### ISSUE THREAD

**Issue by neilyoung** [yzhang-gh/vscode-markdown#477]
I can't even delete a character in time, just for seeing "Running Save Participants" for a while.
Disabling your plugin solves.

**Comment by yzhang-gh** [comment]
This is probably an issue caused by another extension.

Let's do a test.
If you disable all the extensions except for this one (this can be easily done by searching and executing a command named "disable all installed extensions" in the vscode command palette `ctrl+shift+p`, and then enable this extension), do you still have this issue?

If it is no, could you help me pinpoint the "bad" extension? You can enable half of the disabled extensions each time and test, and keep this binary search.

Please let me know if you have any finding.

**Comment by neilyoung** [comment]
@yzhang-gh Sorry, I completely forgot about your request. The answer is: Yes. If I disable all extensions and just enable yours, then the same symptoms are there. I can type, but for instance I can't delete any character with the back arrow. Then, many seconds later, the entered back arrow jumps in and messes up the document.

Can provide a video on a private channel if required.

Weird behaviour goes away, if I disable your extension. I can enter and delete with the back arrow and all in a normal time :)

**Comment by yzhang-gh** [comment]
Then this is probably a performance issue. Is it a big document you are editing?

It would be better if you can provide a CPU profile following the vscode instructions [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions).

**Comment by neilyoung** [comment]
The doc is 1550 lines, 67 kB.
But strange, after some back and forth (disabling/enabling/starting the profiler) I'm now unable to reproduce the problem, even though the extension is enabled.

Could you provide a unique action, by which I can determine exactly, that your extension is working?

**Comment by neilyoung** [comment]
Sorry, seems I have blamed the wrong extension. In fact it is this, who causes the trouble:

https://github.com/bartosz-antosik/vscode-spellright

**Comment by yzhang-gh** [comment]
This is a known conflict with Spell Right, https://github.com/bartosz-antosik/vscode-spellright/issues/273.

Actually, we have nothing to do on this extension side. Hoping it will be resolved there.
