### ISSUE TITLE
[Question] is it possible to select multiple checkbox and mark all as done using shortcut key?

### ISSUE THREAD

**Issue by simkimsia** [yzhang-gh/vscode-markdown#481]
I understand that `Alt + C` toggles the checkbox which is a shortcut that I love.

Is there a way to select a bunch of checkboxes and then toggle the selected checkboxes all at once?

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Given the current implementation, we cannot do this. One solution is to make it support multi-cursor. Although it might be not worth it 😅.

Marking as a feature request.

**Comment by simkimsia** [comment]
Thanks @yzhang-gh I found the code for checkTaskList here https://github.com/yzhang-gh/vscode-markdown/blob/62deb6587e8ee6a146c92897c52a5cd404329f51/src/listEditing.ts#L386

I was wondering how do I "compile" my own forked branch of your code? Because I found this https://stackoverflow.com/a/47251447/80353

I like to give this a try and if it works I can then send a PR.

❤ your extension btw

**Comment by yzhang-gh** [comment]
You will need node.js installed. Open this folder in the vscode, run `npm install`, and then press `F5` (or click the debug view). Note that due to the use of `webpack`, we need to close the debug session and restart it on every code change. (i.e. no live-reload. I haven't found a good way to deal with it)

Below is an example function which supports multi-cursor. Hope it can help you.

https://github.com/yzhang-gh/vscode-markdown/blob/62deb6587e8ee6a146c92897c52a5cd404329f51/src/formatting.ts#L194-L210

Feel free to ask me if you have more questions

**Comment by AskoldMakaruk** [comment]
> Given the current implementation, we cannot do this. One solution is to make it support multi-cursor. Although it might be not worth it 😅.

No support for multi-cursor

**Comment by yzhang-gh** [comment]
Added in v2.5.0

**Comment by simkimsia** [comment]
Thanks!
