### ISSUE TITLE
[Feature Request] Option to turn off auto complete

### ISSUE THREAD

**Issue by Stanzilla** [yzhang-gh/vscode-markdown#566]
#### What is the problem?
I would love to disable auto completingg because it interferes with another extension (TabOut)

#### How can I reproduce it?
N/A

#### Is there any error message in the console?

N/A

**Comment by yzhang-gh** [comment]
Can you elaborate on what exactly the feature you would like to disable?
I am not so sure about your request. Is it about the <kbd>Tab</kbd> key? or about the image/file/math function auto-completion? We don't offer other kinds of completions.

I cannot read your mind. So please fill out the "How can I reproduce it" section and tell me what is the expected outcome. Thanks.

**Comment by Stanzilla** [comment]
As soon as Markdown All in One is installed, writing `[test]` and then pressing TAB no longer tabs me out of the bracket, the main feature of https://marketplace.visualstudio.com/items?itemName=albert.TabOut, instead it autocompletes or adds a tab character

**Comment by yzhang-gh** [comment]
That is because this extension overrides the TAB key (for Markdown list editing).

You can open "keyboard shortcuts" from the left bottom corner, search for "tab" key and remove the command provided by this extension.

![image](https://user-images.githubusercontent.com/7588612/70386257-b5137800-19d2-11ea-9577-0b4856dcb0d5.png)

**Comment by Stanzilla** [comment]
Ohh, thank you!
