### ISSUE TITLE
[Feature Request] PrintToHTML CSS selection

### ISSUE THREAD

**Issue by bcompagnat** [yzhang-gh/vscode-markdown#592]
Hi,

In our team, we would need to use different styling when printing to HTML. There is currently 2 style sheets added in the HTMLs and that makes difficult to overwrite the styles.

It would be nice to have a setting that allows us to select the css.. maybe either defaults/none or a path entry.

For now we add a css html link at the top of our MD but its not overwriting the previous ones.

Thank you for your time.

**Comment by yzhang-gh** [comment]
Have you tried the `markdown.styles` option?
(It has some restrictions. To my memory, `https` links and local CSS files in the current folder are allowed.)

The thing is we need to make sure the exported HTML looks (almost) the same as in VSCode. Otherwise, it will be confusing as you can't see how it looks like before you print it.

**Comment by yzhang-gh** [comment]
Please see #598 for a working example.
