### ISSUE TITLE
Table Formatter is doing nothing

### ISSUE THREAD

**Issue by amaridev** [yzhang-gh/vscode-markdown#606]
Using Windows, the Shortcut Alt + Shift + F is doing nothing. 
Table Formatter in Settings is enabled of course. No other formaters are installed. 

On Windows Marketplace advertised table formating is not working. Did it get removed from the plugin?

**Comment by yzhang-gh** [comment]
At least you need to provide a sample code snippet for testing.

**Comment by AdamHoej-au** [comment]
`Left|Center|Right
1|2|3
8|7|9`

I tried this - with no luck

**Comment by yzhang-gh** [comment]
Please see [GitHub Flavored Markdown Spec](https://github.github.com/gfm/#tables-extension-) for the table syntax.

**Comment by vaidik** [comment]
I have a similar issue. This doesn't seem to work for me. Here is the my code snippet:

```
Name | Areas of Expertise | Vouched References
:---- | :------| :-----
Name 1 | Design, Product Engineering, Mobile | Comp 1
Name 2 | Product Engineering, Systems Engineering, Functional Programming | Comp 2, Comp 3
```

When I press Alt + Shift + F (on Mac), it just prints this special character: ` ̰`. Seems like there is a conflict between the keyboard layout and the key binding.

Any thoughts on how I can solve this?

**Comment by Lemmingh** [comment]
@vaidik

macOS can prevent VS Code from receiving key bindings.

https://github.com/microsoft/vscode/issues/144847#issuecomment-1065135238

**Comment by vaidik** [comment]
> @vaidik
> 
> macOS can prevent VS Code from receiving key bindings.
> 
> [microsoft/vscode#144847 (comment)](https://github.com/microsoft/vscode/issues/144847#issuecomment-1065135238)

Well wouldn't it be better that we use some other shortcut in that case? There would be a lot of users on Mac suffering this. Is there a workaround for this feature?

**Comment by yzhang-gh** [comment]
That is the default key binding to the "format document" command which is provided by VS Code. This extension only registers a "formatter" with VS Code _internally_.

You can either open a request (to change the defaults) in the VS Code repo, or [change your user `keybindings.json`](https://code.visualstudio.com/docs/getstarted/keybindings).

**Comment by Lemmingh** [comment]
@vaidik 's problems and questions root in macOS. The issues I mentioned above can answer all of them. To be specific:

* <https://github.com/microsoft/vscode/issues/144847#issuecomment-1065135238>
* <https://github.com/microsoft/vscode/issues/41024#issuecomment-439321044>
* <https://crbug.com/887519>

---

The `Shift+Option+F` is [VS Code's built-in key binding](https://code.visualstudio.com/docs/getstarted/keybindings) for "Format Document" (`editor.action.formatDocument`). It's entirely provided by VS Code.

VS Code's default shortcuts work on standard US QWERTY keyboards at least, but may behave abnormally on other layouts, such as US-International and India ABC.

The VS Code team is aware of the problem, but **unable to tackle it**. Because it's an upstream issue. Even Chromium has no idea of bypassing the constraint from macOS.

---

macOS has a well-known powerful opinionated keyboard mapping mechanism. It can forcefully trap a key combination, and literally emit the output defined in the layout file.

macOS's built-in layouts collectively come with hundreds of actions involving the `Option` key. And we sometimes call them "Alt Code Shortcuts". They're so famous that people are supposed to know their existence before purchasing a Mac.

If you have any question about the inherent behavior of macOS, please contact Apple Support.

---

The most reliable way to get rid of macOS's default mapping is **crafting your own keyboard layout**.

There're a number of detailed discussions on Stack Overflow and GitHub. Meanwhile, **Ukelele** by SIL may help you a lot to make a custom keyboard layout.
