### ISSUE TITLE
the \tag{n} and --- have wrong position

### ISSUE THREAD

**Issue by wuyudi** [yzhang-gh/vscode-markdown#657]
#### What is the problem?

The line seems may be under the (1) ?

![image](https://user-images.githubusercontent.com/30024051/79638567-989ffd00-8175-11ea-9222-52208f5af3bf.png)

If I type $$a\tag{1}$$ , the problem disappeared.

#### How can I reproduce it?

```
$$\tag{1}$$

---

```

I don't know if this is a problem. Since it doesn't bother me.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I checked and it did look weird.

It seems to be more of a CSS limitation (the tag should [float](https://developer.mozilla.org/en-US/docs/Web/CSS/float) right). When there is any math expression, it works well.

![image](https://user-images.githubusercontent.com/7588612/79639816-931bd480-81c0-11ea-8d8c-86d08b674e49.png)

**Comment by Lemmingh** [comment]
So far, in KaTeX 0.11.1, `\tag` is compiled to a `<span>` with style

```css
.katex-display > .katex > .katex-html > .tag {
  position: absolute;
  right: 0;
}
```

The element is *absolutely positioned*, that's, it is *removed* from the normal document flow, and *no space* is created for the element in the page layout.

Specifically, when there is only `$$\tag{1}$$`, the height of the container (KaTeX display math area) is **zero**.

Then, the next element in the document comes up and overlaps the container.

---

I think `float` is *not* a good solution, because a `float` element still occupies some space in the page layout, causing problems such as

* The equation on the same line is not centered.
* When the equation is very long, the `tag` can go to another line.

---

This issue might be related to KaTeX/KaTeX#1983.

**Comment by yzhang-gh** [comment]
Thanks for the information. Closing as it can only be solved by KaTeX.
