### ISSUE TITLE
Automatic insertion of bullet points is unreliable

### ISSUE THREAD

**Issue by dschuessler** [yzhang-gh/vscode-markdown#715]
#### What is the problem?

Insertions of bullet sometimes happens:
* after indenting with Tab so that the bullet point does not move along with the cursor
* or not at all

#### How can I reproduce it?

With a bit of patience and good timing as shown in this GIF. If you regularly write deeply nested bullet point lists you notice it happening about 1 of 25 times. Nothing tragic, but mildly annoying.

![Ohne Titel 2020-06-02 23_43_31](https://user-images.githubusercontent.com/5774545/83574695-456be900-a52e-11ea-87e5-95b85c133f86.gif)

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
Can you disable all other extensions and try again? It works stably on my PC. (Your line numbers looks different from a regular setting.)

**Comment by dschuessler** [comment]
I actually failed to reproduce this with extensions turned off. I used to use the Vim extension and since switched to https://github.com/asvetliakov/vscode-neovim which seemingly reduced the frequency of this issue, but right now it happened again.

I don't know how possibly to check the influence of every extension I use on the frequency of this issue. I guess somewhere deep down there is some kind of race condition.

**Comment by yzhang-gh** [comment]
I guess the Vim extension is the reason as both it and this extension listen to the "onEnterKey" event and do some edits according to the context. This extension tries to avoid such a conflict by checking the Vim mode

https://github.com/yzhang-gh/vscode-markdown/blob/bbada83b39a6ef862e59da0696847d953757ee23/package.json#L122

`vim.mode != 'Normal' && vim.mode != 'Visual' && vim.mode != 'VisualBlock' && vim.mode != 'VisualLine' && vim.mode != 'SearchInProgressMode' && vim.mode != 'CommandlineInProgress' && vim.mode != 'Replace' && vim.mode != 'EasyMotionMode' && vim.mode != 'EasyMotionInputMode' && vim.mode != 'SurroundInputMode'`

---

I realized you are using `asvetliakov.vscode-neovim` rather than [`vscodevim.vim`](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)

Please also check https://github.com/asvetliakov/vscode-neovim#performancelatency-problems. It is common that a Vim extension conflicts with some extensions because of the mechanism.

**Comment by dschuessler** [comment]
I see. Do I understand correctly that it is out of the control of extension authors to address such behavior? In that case I’d try escalating the issue to the VSCode maintainers as it would be framed more aptly as an issue with the extension system rather than a particular extension.

**Comment by yzhang-gh** [comment]
> Do I understand correctly that it is out of the control of extension authors to address such behavior?

Exactly. For a single extension, it overrides any key it wants to change. Usually different extensions won't conflict as we have `context` variables. However, I guess the `context` updating cannot catch up with your typing speed in this case.

> In that case I’d try escalating the issue to the VSCode maintainers as it would be framed more aptly as an issue with the extension system rather than a particular extension.

I agree although I don't think there is a good solution now (and it is hard to tell what VSCode should do to improve this situation). The Vim extensions are eventually **simulators** on VSCode and some performance(-related/caused) issues are expected.

**Comment by yzhang-gh** [comment]
Close as there is not much we can do on this side.
