### ISSUE TITLE
Allow enabling/disabling code block and strikethrough decorations separetly

### ISSUE THREAD

**Issue by segevfiner** [yzhang-gh/vscode-markdown#757]
The extension currently provides `markdown.extension.syntax.decorations` to enable/disable both the strike through and code block decorations. It would be nice to have a setting to disable one or the other separately. e.g. Only disable code block decorations without disabling strike through decorations.

**Comment by yzhang-gh** [comment]
Well, it is so small a configuration. Probably you can disable `decorations` provided by this extension and use [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) to get the result. It is quite useful, I use it all the time.

As for the regex, just use `(~~.+?~~)`.

**Comment by chaojian-zhang** [comment]
Hi I am just wondering is there a color for code block? Because in my syntax highlight I can only see color decorations for inline code and not in code blocks:

![Image 20201031 162616](https://user-images.githubusercontent.com/7077098/97789311-d1de0e80-1b95-11eb-8bf8-05a217788596.png)

Can you please show what the configuration is for that?

Thanks!

**Comment by yzhang-gh** [comment]
You need to specify a language id for the code block.

**Input**

<pre>```ini
[client]
set=utf-8
```</pre>

**Output**

```ini
[client]
set=utf-8
```

**Comment by chaojian-zhang** [comment]
Brilliant! Thanks for reply.
