### ISSUE TITLE
Jump to word when double-clicked on preview tab

### ISSUE THREAD

**Issue by samuelpetroline** [yzhang-gh/vscode-markdown#762]
I was wondering if there is any way to jump to a word when the respective word is double-clicked on the preview tab?

If not, is PR welcome?

Thanks for the extension, is amazing!

**Comment by yzhang-gh** [comment]
Thank you.

VSCode itself has [an attempt](https://code.visualstudio.com/docs/languages/markdown#_editor-and-preview-synchronization) that synchronizes the source editor and the preview pane, although it is problematic in practice 😔.

Actually I had the same idea as yours (double-click to sync, on both side) this morning when I was editing the long `README` of this extension. But for me it doesn't have a high priority because I don't use the preview tab that often.

> If not, is PR welcome?

Of course. And probably you can borrow some code from LaTeX Workshop which has the feature.

**Comment by samuelpetroline** [comment]
VSCode sync is good but could be more feature-rich. Guess is not the primary use for this.

I will be looking into this then. Thanks for the info and the example.

**Comment by DAmNRelentless** [comment]
I'd love to see this as well. :)

**Comment by Lemmingh** [comment]
Unfortunately, [this cannot be solved on our side](https://github.com/microsoft/vscode/issues/122961#issuecomment-832300619).

Please turn to <https://github.com/microsoft/vscode/issues/131639>

---

[LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop/wiki/View) makes it thanks to the precise source map provided by [SyncTeX and the toolchain](https://tex.stackexchange.com/q/118489):

> we ask TeX to report for each box the stored file name, the stored line number, the horizontal and vertical positions, and the dimensions as computed during typesetting.
>
> we also ask TeX to store input records for glue items, because they are created in TeX’s mouth, when the current input record is still accurate.

---

But `markdown-it`'s is very [rough](https://github.com/markdown-it/markdown-it/issues/374#issuecomment-311094646):

> End line in `map` is a line when the rule terminates itself
>
> Very limited implementation, restricted by current architecture

---

A solution might be fuzzy search in a range.
