### ISSUE TITLE
Option to open preview to bottom

### ISSUE THREAD

**Issue by TakingItCasual** [yzhang-gh/vscode-markdown#767]
Based on this SO post: https://stackoverflow.com/q/56655288

Currently, the only provided option is to open a preview to the side.

I use the `multi-command` extension to combine the 2 commands in the SO post's answer, and set a new keybinding to open a preview to the bottom. I'm suggesting a native option that'd change the appearance & functionality of the "Open Preview to the Side" button to "Open Preview to the Bottom".

**Comment by yzhang-gh** [comment]
This extension invokes command `markdown.showPreviewToSide` which is provided by VSCode itself. Probably you need to file an issue there.

(I don't think changing the editor group layout is a good solution. But I can leave this issue open as a feature request.)

**Comment by Lemmingh** [comment]
* [The preview is provided and owned by VS Code.](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview)

* [VS Code API is abstract and not aware of concrete UI layout.](https://code.visualstudio.com/api/references/vscode-api#ViewColumn)

* Since VS Code extensions cannot know concrete UI layout, if we sent lots of commands blindly, there could be problems more severe than #144

---

If "open to the bottom" is a common case for you, please set:

```json
"workbench.editor.openSideBySideDirection": "down"
```
