### ISSUE TITLE
Error "command 'markdown.extension.onXXXKey' not found"

### ISSUE THREAD

**Issue by rich-fts** [yzhang-gh/vscode-markdown#796]
#### What is the problem?

I am getting the markdown extension key not found error.  I have reloaded VS Code.  I have uninstalled and re-installed the extension.  I continue to get the error.  At this point I had to leave the extension uninstalled so that I can do my work.

#### How can I reproduce it?

Load VS Code and the extension.  Edit a file and click enter to create a new line.

#### Is there any error message in the console?

Yes - the above error message for the enter key is what I am getting.

**Comment by yzhang-gh** [comment]
This is weird.

1. Can you check again with all other extensions disabled? (In case there is a conflict with any other extension)

   ![image](https://user-images.githubusercontent.com/7588612/91367919-3e592c00-e83a-11ea-951b-50472f137c54.png)

2. Also, in case this is because of corrupted installation, make sure to **restart** VSCode after you uninstall this extension. (Extensions are only removed on the next VSCode start.) And then reinstall this extension.

**Comment by rich-fts** [comment]
Hi – I just switched laptops and re-installed your extension which is now working fine on the new laptop.  I will see if I can play around on my old one to recreate the issue, but you can close this for now.

**Comment by yzhang-gh** [comment]
Thanks for the update.
