### ISSUE TITLE
Activating(Enabling) extension causes loop (Trouble)

### ISSUE THREAD

**Issue by bsnresearcher** [yzhang-gh/vscode-markdown#815]
My trouble is  that causes loop of activating(enabling) addons when start input after opened markdown file.

It does not complete(finish), VSCode tries to enable activating extension infinitely. So I could not start input/modify the markdown file.

I found this trouble was caused exclusively [VSCodeVim](https://github.com/VSCodeVim/Vim) and this vscode-markdown addon. (That is, if one addon of the two becomes disable, this trouble does not occur).

What should I do for solve?

![image](https://user-images.githubusercontent.com/34906909/93156650-81c0ff00-f743-11ea-8abc-ee8a4d738025.png)

**Comment by bsnresearcher** [comment]
Supplement describe:

This trouble seems to be occurred when complex or/and big size markdown.

The complexity indicates inclusion of code description using TOC function or using ```script``` func and so on.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Can you install [this build](https://github.com/yzhang-gh/vscode-markdown/files/5225817/maio-3.3.0-debug.zip) (packaged for debugging) and make a CPU profile (following [this instruction](https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)). That will help a lot to pinpoint the root cause.

(For instructions about `.vsix`, please see [here](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).)

**Comment by bsnresearcher** [comment]
Thank you very much. Now the trouble have not been occurred. 
Please would reflect the improvement of this add-on into next version.

**Comment by bsnresearcher** [comment]
After that, I was aware outline of markdown was not shown.

This trouble might be caused I changed a lot of configuration before the author gave me the fixed add-on.

Was this trouble caused from the fixed add-on? (For example, might the fixed add-on be disabled the outline showing function to solve my problem?)

Otherwise, can I fix the outline disable problem  by changing my configuration in my VSCode.

**Comment by yzhang-gh** [comment]
> Thank you very much. Now the trouble have not been occurred.
> Please would reflect the improvement of this add-on into next version.

Well, I changed nothing (in theory). The debugging version can be viewed as an **uncompressed** version. (With the compressed version we cannot inspect the CPU profile.)

> After that, I was aware outline of markdown was not shown.

This extension stopped providing the outline view a long time ago (because VSCode did it itself). Probably you need to check your VSCode settings.
