### ISSUE TITLE
Backspace delay or ignored

### ISSUE THREAD

**Issue by FlightPassage** [yzhang-gh/vscode-markdown#816]
#### What is the problem?
When pressing backspace to remove characters there is a up to 5 second delay. This tends to get longer the longer the document is open. In the worst case this keystroke or pressed gets entirely ignored. Which means that errors have to be cut out of document in order to allow me to retype them.

#### How can I reproduce it?
In a larger document, I started to notice this around a 10 page markdown document the delay starts. As you press backspace you will start to notice larger and larger delay when this extension is enabled. 

In Larger markdown documents the delay seems to get longer and longer. This compounds the longer that this document is being edited. At the current moment I am editing and adding to a 2843 line markdown file. 

#### Is there any error message in the console?

None that deal with Markdown extensions.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

But I am not sure whether it is because of something other than this extension.
A simple way is to try again with all other extensions disabled.
You can also install [this build](https://github.com/yzhang-gh/vscode-markdown/files/5225817/maio-3.3.0-debug.zip) (packaged for debugging) and make a CPU profile (following [this instruction](https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)). That will help a lot to pinpoint the root cause.

(For instructions about `.vsix`, please see [here](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).)

**Comment by R-U-Airil** [comment]
In my case, pressing Backspace or Enter just take no effect at all, with a hint "command 'markdown.extension.onBackSpaceKey' not found"/"command 'markdown.extension.onEnterKey' not found". I've tried the debug version above and it doesn't help.
