### ISSUE TITLE
Can not render the $$...$$ block of KaTex if the first $$ is not the beginning of the line 

### ISSUE THREAD

**Issue by BlueHeart0621** [yzhang-gh/vscode-markdown#839]
## Problem
Can not render the `$$...$$` block of KaTex if the first `$$` is not the beginning of the line.
For example, if there are words before the first `$$`
```
abc $$
a = b
$$ def
```
it cannot render the math formula.

**Comment by Lemmingh** [comment]
If I recall correctly, it was by design.

---

Personally, allowing to embed *display math area* inside normal Markdown paragraphs would be extremely **dangerous**.

From the perspective of rendering, [`markdown-it-katex`](https://github.com/yzhang-gh/markdown-it-katex/blob/c77efb25e3e5eb3367b45077cc7c1473908fedc1/index.js) would be much more error-prone.

From the perspective of editing, creating *TextMate grammars* for such syntax is also a bad idea.

I'd recommend you to have a look at

* [markdown-it's development guide](https://github.com/markdown-it/markdown-it/tree/master/docs)
* <https://github.com/yzhang-gh/vscode-markdown/issues/552#issuecomment-578932184>
* John MacFarlane's [Beyond Markdown](https://talk.commonmark.org/t/beyond-markdown/2787)

---

If you really need *display style math* in a paragraph, a nice practice is the [`\displaystyle`](https://www.tutorialspoint.com/tex_commands/displaystyle.htm) command. For example:

```markdown
The optical path length in such medium is ${ \displaystyle [l] = \sum_{i}^{k}{ n_i l_i } }$.
```
