### ISSUE TITLE
Priority of $~~$

### ISSUE THREAD

**Issue by scbzfarmingtest** [yzhang-gh/vscode-markdown#906]
When using $~~$ to creat spaces, outcomes are great. However, the auto-preveiw for coding page will more likely to take it as words with strikethroughs, which should be of syntax \~\~word\~\~.

P.S. I am totally amateur. I guess this is a priority problem. Sorry for my poor English and GREAT THANKS!!!

**Comment by yzhang-gh** [comment]
Can you provide an example: a piece of text (such as `some $~~$ text`?), what is expected, what does it look like (in the source code tab or in the preview tab?)

**Comment by scbzfarmingtest** [comment]
Sorry I didnt make it clear. The preview appears great, while source code gives a different look.
Here is an example screenshot.
![屏幕截图(4)](https://user-images.githubusercontent.com/68948943/109022895-3bf76200-76f7-11eb-8f70-4a8fedf0ffd9.png)

You can try it by the codes below as well

> This is an example. \<\/br\> \$\~\~\$ This is an example. \<\/br\> \$\~\~\~\~\$ This is an example.
>
> \~\~ Stikethrough \~\~
>
> \$\~\~\$ \$\Leftrightarrow\$ \TAB

**Comment by yzhang-gh** [comment]
Thanks.

You are right that this is a bug... although this case should already be considered.

https://github.com/yzhang-gh/vscode-markdown/blob/73b8f50e3ca166f257074563d6adc59054773db3/src/syntaxDecorations.ts#L167-L169

We probably won't fix this as we may rework this feature later.

You can(/should) use something like `&nbsp;` or `&emsp;` (rather than inline math) to create space in Markdown.

**Comment by scbzfarmingtest** [comment]
Thanks! Gratitude for  your effort!
