### ISSUE TITLE
The editor goes wobbly when in preview

### ISSUE THREAD

**Issue by schtonn** [yzhang-gh/vscode-markdown#961]
## Problem
Every time I edit long documents (about 200 lines) with formulas, and with preview open, the preview wobbles up and down as I type, and the editor wobbles simultaneously. On the whole, it scrolls upward until the cursor is out of range, so I can hardly see what I am typing.

I've tested a few times, and it seems this mostly happens when I type in blank characters such as enter or space.

**Comment by Lemmingh** [comment]
The preview is provided by VS Code's built-in feature.

As far as I know, it is very likely from the nature of web browser.

You can disable auto scrolling:

* `markdown.preview.scrollPreviewWithEditor`
* `markdown.preview.scrollEditorWithPreview`

**Comment by schtonn** [comment]
Thank you very much. The problem does not reappear when I uninstalled the extension though. Maybe it is some problem with LaTeX?

Well, you can close this if it really has nothing to do with the extension.

**Comment by yzhang-gh** [comment]
Feel free to comment again if you find more information.

**Comment by Lemmingh** [comment]
I now believe this is caused by layout changes triggered by **web font loading**.

Web browsers repaint elements when KaTeX fonts are loaded, causing `scroll` events.

VS Code's Markdown preview manages to know [image loading](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete). (<https://github.com/microsoft/vscode/pull/111094>)

But I'm afraid there is no way to monitor font loading, unless attaching a debugger to the browser.
