### ISSUE TITLE
Code blocks side-by-side

### ISSUE THREAD

**Issue by Cicero-Ribeiro** [yzhang-gh/vscode-markdown#987]
## Proposal

I would like have the option to render two small code blocks side-by-side on my Markdown document, 
I intend to show code - output side-by-side on my documentation.

## References

Currently i use a HTML Table solution, but i find it to complex, and it leave the .md file unclear.
Optimal I would like to can define the column width (for a 02 columns table). No Title (column header) are needed.

Thank you

**Comment by yzhang-gh** [comment]
Markdown doesn't have such a kind of syntax.

Please see https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported

Also copied some text from another issue.

> You are asking for an extension to the Markdown syntax (similar to [Markdown footnotes](https://github.com/markdown-it/markdown-it-footnote)).
>
> In VS Code, Markdown is rendered by the [`markdown-it`](https://github.com/markdown-it/markdown-it) engine. This repo (Markdown All in One) doesn't introduce any new Markdown syntax but only uses existing `markdown-it` extensions (e.g. `markdown-it-footnote`, `markdown-it-task-list`).

**Comment by Cicero-Ribeiro** [comment]
Thank you

**Comment by Lemmingh** [comment]
Indeed, it's not about rendering option, but needs dedicated syntax, probably some kind of containers.

If you are not going to look for such a Markdown flavor, however, it can be achieved easily with HTML custom elements and CSS, which should be much more elegant than HTML table. CommonMark will recognize custom tags as type 7 HTML blocks.

``````markdown
<code-group>
<code-group-item>

```javascript
console.log("Morning!"); ///////////////////////////////////////////////////////
```

</code-group-item>
<code-group-item>

```text
Morning!
```

</code-group-item>
</code-group>
``````

``````css
code-group {
    align-items: stretch;
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    justify-content: space-around;
    width: 100%;
}

code-group-item {
    display: block;
    overflow-x: scroll;
    width: calc(50% - 8px);
}

@media (max-width: 40em) {
    code-group {
        flex-direction: column;
    }

    code-group-item {
        width: calc(100% - 8px);
    }
}
``````

---

Keep the following in mind when taking advantage of HTML custom elements. (Might be a bit technical.)

Generally speaking, create custom elements only when you need reusable building blocks with custom logic, and the existing HTML elements cannot meet your need. For example, GitHub's `<relative-time>` is implemented in this way.

For simple presentation, `<div>` is often enough:

``````html
<div class="code-group">

</div>
``````

``````css
.code-group {
}
``````

The name of a custom element:

* must be of kebab-case (all-lower-with-hyphen)

* must contain hyphen

* must not be any of the names from SVG and MathML.

Otherwise, they may be parsed surprisingly.

Although the HTML Standard asks authors to register their custom elements in principle:

``````javascript
class CodeGroupElement extends HTMLElement {
    constructor() {
        super();
    }
}

class CodeGroupItemElement extends HTMLElement {
    constructor() {
        super();
    }
}

window.customElements.define("code-group", CodeGroupElement);
window.customElements.define("code-group-item", CodeGroupItemElement);
``````

you don't have to, if you only use them (as undefined elements) in place of `<span>` or `<div>`, because the Standard requires web browsers to treat elements with valid custom element name as instances of `HTMLElement` by default.
